CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    family_id UUID NOT NULL,
    device_id VARCHAR(128) NOT NULL,
    rotated_at TIMESTAMPTZ,
    replacement_ciphertext TEXT,
    replacement_expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_refresh_tokens_token_hash
        UNIQUE (token_hash),
    CONSTRAINT ck_refresh_tokens_hash_length
        CHECK (char_length(token_hash) = 64),
    CONSTRAINT ck_refresh_tokens_replacement_pair
        CHECK (
            (replacement_ciphertext IS NULL AND replacement_expires_at IS NULL)
            OR
            (replacement_ciphertext IS NOT NULL AND replacement_expires_at IS NOT NULL AND rotated_at IS NOT NULL)
        )
);

CREATE INDEX idx_refresh_tokens_user_device_active
    ON refresh_tokens (user_id, device_id)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_refresh_tokens_family_active
    ON refresh_tokens (family_id)
    WHERE revoked_at IS NULL;

CREATE TABLE legacy_identity_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_id VARCHAR(128) NOT NULL,
    anonymous_user_id BIGINT NOT NULL,
    claimed_by_user_id BIGINT NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_legacy_identity_claims_installation
        UNIQUE (installation_id),
    CONSTRAINT uk_legacy_identity_claims_anonymous_user
        UNIQUE (anonymous_user_id),
    CONSTRAINT fk_legacy_identity_claims_anonymous_user
        FOREIGN KEY (anonymous_user_id)
        REFERENCES users (id),
    CONSTRAINT fk_legacy_identity_claims_claimed_by_user
        FOREIGN KEY (claimed_by_user_id)
        REFERENCES users (id),
    CONSTRAINT ck_legacy_identity_claims_distinct_users
        CHECK (anonymous_user_id <> claimed_by_user_id)
);

CREATE INDEX idx_legacy_identity_claims_claimed_by_user
    ON legacy_identity_claims (claimed_by_user_id, claimed_at DESC);

CREATE TABLE registration_approval_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ticket_hash VARCHAR(64) NOT NULL,
    terminal_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_registration_approval_tickets_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_registration_approval_tickets_user
        UNIQUE (user_id),
    CONSTRAINT uk_registration_approval_tickets_hash
        UNIQUE (ticket_hash),
    CONSTRAINT ck_registration_approval_tickets_hash_length
        CHECK (char_length(ticket_hash) = 64)
);

CREATE INDEX idx_registration_approval_tickets_terminal_expiry
    ON registration_approval_tickets (terminal_expires_at)
    WHERE terminal_expires_at IS NOT NULL;

CREATE TABLE account_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    target_user_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    before_state JSONB,
    after_state JSONB,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_account_audit_logs_actor_user
        FOREIGN KEY (actor_user_id)
        REFERENCES users (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_account_audit_logs_target_user
        FOREIGN KEY (target_user_id)
        REFERENCES users (id),
    CONSTRAINT ck_account_audit_logs_action
        CHECK (action IN (
            'APPROVE', 'REJECT', 'DISABLE', 'ENABLE', 'PROMOTE', 'DEMOTE',
            'REVOKE_SESSIONS', 'RESET_PASSWORD', 'CHANGE_PASSWORD',
            'OWNER_FORCE_RESET', 'LEGACY_CLAIM'
        ))
);

CREATE INDEX idx_account_audit_logs_target_created
    ON account_audit_logs (target_user_id, created_at DESC);

CREATE INDEX idx_account_audit_logs_actor_created
    ON account_audit_logs (actor_user_id, created_at DESC)
    WHERE actor_user_id IS NOT NULL;
