CREATE TABLE uploaded_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key VARCHAR(512) NOT NULL,
    thumbnail_object_key VARCHAR(512),
    owner_user_id BIGINT NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_uploaded_objects_object_key UNIQUE (object_key),
    CONSTRAINT fk_uploaded_objects_owner FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT ck_uploaded_objects_size_nonnegative CHECK (size_bytes >= 0)
);

CREATE INDEX idx_uploaded_objects_owner_created ON uploaded_objects (owner_user_id, created_at DESC);
