CREATE TABLE review_config_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word VARCHAR(128) NOT NULL,
    word_type VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    source VARCHAR(32) NOT NULL DEFAULT 'manual',
    remark TEXT,
    updated_by VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_review_config_words_word_type UNIQUE (word, word_type)
);

CREATE INDEX idx_review_config_words_enabled_word_type
    ON review_config_words (enabled, word_type);

CREATE TABLE review_config_word_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_config_word_id BIGINT NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    before_value JSONB,
    after_value JSONB,
    operator_id VARCHAR(64),
    operator_name VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_config_word_audit_logs_word
        FOREIGN KEY (review_config_word_id)
        REFERENCES review_config_words (id),
    CONSTRAINT ck_review_config_word_audit_logs_action_type
        CHECK (action_type IN ('create', 'update', 'enable', 'disable'))
);

CREATE INDEX idx_review_config_word_audit_logs_word_id
    ON review_config_word_audit_logs (review_config_word_id);

CREATE INDEX idx_review_config_word_audit_logs_created_at
    ON review_config_word_audit_logs (created_at DESC);
