CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(64),
    avatar VARCHAR(512),
    phone VARCHAR(32),
    email VARCHAR(255),
    auth_provider VARCHAR(32) NOT NULL DEFAULT 'anonymous',
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_auth_provider
        CHECK (auth_provider IN ('anonymous', 'phone', 'email', 'wechat', 'apple', 'google')),
    CONSTRAINT ck_users_status
        CHECK (status IN ('active', 'disabled', 'deleted'))
);

CREATE INDEX idx_users_auth_provider_status
    ON users (auth_provider, status);

CREATE TABLE food_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    alias TEXT,
    category VARCHAR(64) NOT NULL,
    subcategory VARCHAR(64),
    brand VARCHAR(128),
    barcode VARCHAR(64),
    source VARCHAR(32) NOT NULL,
    audit_status VARCHAR(32) NOT NULL,
    search_keywords TEXT NOT NULL DEFAULT '',
    report_count INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    cover_image_url VARCHAR(512),
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    nutrition_info JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_food_items_item_type
        CHECK (item_type IN ('packaged_product', 'dish', 'fruit')),
    CONSTRAINT ck_food_items_source
        CHECK (source IN ('system', 'user_generated', 'external_api')),
    CONSTRAINT ck_food_items_audit_status
        CHECK (audit_status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT ck_food_items_report_count
        CHECK (report_count >= 0)
);

CREATE UNIQUE INDEX uk_food_items_packaged_barcode
    ON food_items (barcode)
    WHERE barcode IS NOT NULL AND item_type = 'packaged_product';

CREATE INDEX idx_food_items_audit_status
    ON food_items (audit_status);

CREATE INDEX idx_food_items_name_trgm
    ON food_items
    USING gin (name gin_trgm_ops);

CREATE INDEX idx_food_items_alias_trgm
    ON food_items
    USING gin (alias gin_trgm_ops);

CREATE INDEX idx_food_items_search_keywords_trgm
    ON food_items
    USING gin (search_keywords gin_trgm_ops);

CREATE TABLE food_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_item_id BIGINT NOT NULL,
    image_url VARCHAR(512) NOT NULL,
    thumbnail_url VARCHAR(512),
    image_type VARCHAR(32),
    width INTEGER,
    height INTEGER,
    embedding_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_food_images_food_item
        FOREIGN KEY (food_item_id)
        REFERENCES food_items (id),
    CONSTRAINT ck_food_images_width
        CHECK (width IS NULL OR width > 0),
    CONSTRAINT ck_food_images_height
        CHECK (height IS NULL OR height > 0),
    CONSTRAINT ck_food_images_embedding_status
        CHECK (embedding_status IN ('pending', 'processing', 'completed', 'failed'))
);

CREATE INDEX idx_food_images_food_item_id
    ON food_images (food_item_id);

CREATE TABLE food_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    food_item_id BIGINT NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    sync_status VARCHAR(32) NOT NULL DEFAULT 'synced',
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    rating SMALLINT NOT NULL,
    comment TEXT,
    price NUMERIC(10, 2),
    location VARCHAR(255),
    record_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_food_records_user
        FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_food_records_food_item
        FOREIGN KEY (food_item_id)
        REFERENCES food_items (id),
    CONSTRAINT ck_food_records_source_type
        CHECK (source_type IN ('text_search', 'image_search', 'manual')),
    CONSTRAINT ck_food_records_sync_status
        CHECK (sync_status IN ('draft', 'syncing', 'synced', 'failed')),
    CONSTRAINT ck_food_records_rating
        CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_food_records_price
        CHECK (price IS NULL OR price >= 0)
);

CREATE INDEX idx_food_records_user_record_time
    ON food_records (user_id, record_time DESC);

CREATE INDEX idx_food_records_food_item_record_time
    ON food_records (food_item_id, record_time DESC);

CREATE TABLE food_record_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL,
    image_url VARCHAR(512) NOT NULL,
    thumbnail_url VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_food_record_images_record
        FOREIGN KEY (record_id)
        REFERENCES food_records (id)
);

CREATE INDEX idx_food_record_images_record_id
    ON food_record_images (record_id);

CREATE TABLE recognition_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    input_image_url VARCHAR(512) NOT NULL,
    status VARCHAR(32) NOT NULL,
    top_candidates JSONB NOT NULL DEFAULT '[]'::jsonb,
    selected_food_item_id BIGINT,
    confidence NUMERIC(5, 4),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    CONSTRAINT fk_recognition_tasks_user
        FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_recognition_tasks_selected_food_item
        FOREIGN KEY (selected_food_item_id)
        REFERENCES food_items (id),
    CONSTRAINT ck_recognition_tasks_status
        CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    CONSTRAINT ck_recognition_tasks_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE INDEX idx_recognition_tasks_user_created_at
    ON recognition_tasks (user_id, created_at DESC);

CREATE INDEX idx_recognition_tasks_status_created_at
    ON recognition_tasks (status, created_at DESC);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    tag_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tags_name_tag_type UNIQUE (name, tag_type)
);

CREATE INDEX idx_tags_tag_type
    ON tags (tag_type);
