INSERT INTO food_items (
    name,
    item_type,
    alias,
    category,
    subcategory,
    brand,
    barcode,
    source,
    audit_status,
    search_keywords,
    description,
    cover_image_url,
    tags
) VALUES
    (
        '乐事黄瓜味薯片',
        'packaged_product',
        '乐事黄瓜味',
        'snack',
        'chips',
        '乐事',
        '6900000000011',
        'system',
        'approved',
        '乐事 薯片 黄瓜味 青瓜味 potato chips',
        '冷启动样例数据：常见包装零食。',
        NULL,
        '["snack","chips"]'::jsonb
    ),
    (
        '奥利奥原味夹心饼干',
        'packaged_product',
        '奥利奥 原味',
        'snack',
        'biscuit',
        '奥利奥',
        '6900000000012',
        'system',
        'approved',
        '奥利奥 夹心 饼干 原味 oreo biscuit',
        '冷启动样例数据：常见包装零食。',
        NULL,
        '["snack","biscuit"]'::jsonb
    ),
    (
        '无糖拿铁',
        'dish',
        '冰拿铁',
        'drink',
        'coffee',
        'SNK Cafe',
        NULL,
        'system',
        'approved',
        '拿铁 latte 咖啡 无糖 冰咖啡',
        '冷启动样例数据：现制饮品。',
        NULL,
        '["coffee","drink"]'::jsonb
    ),
    (
        '抹茶蛋糕',
        'dish',
        '抹茶奶油蛋糕',
        'dessert',
        'cake',
        'SNK Bakery',
        NULL,
        'system',
        'approved',
        '抹茶 蛋糕 甜品 cake dessert',
        '冷启动样例数据：甜品。',
        NULL,
        '["dessert","cake"]'::jsonb
    ),
    (
        '牛肉汉堡',
        'dish',
        '经典牛肉堡',
        'meal',
        'burger',
        'SNK Burger',
        NULL,
        'system',
        'approved',
        '牛肉 汉堡 burger meal fast food',
        '冷启动样例数据：快餐主食。',
        NULL,
        '["burger","meal"]'::jsonb
    ),
    (
        '海南芒果',
        'fruit',
        '台农芒',
        'fruit',
        'mango',
        NULL,
        NULL,
        'system',
        'approved',
        '芒果 mango 水果 海南',
        '冷启动样例数据：水果。',
        NULL,
        '["fruit","mango"]'::jsonb
    );
