CREATE TABLE food_item_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_item_id BIGINT NOT NULL,
    reporter_user_id BIGINT NOT NULL,
    reason VARCHAR(2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_food_item_reports_food_item
        FOREIGN KEY (food_item_id)
        REFERENCES food_items (id),
    CONSTRAINT fk_food_item_reports_reporter_user
        FOREIGN KEY (reporter_user_id)
        REFERENCES users (id)
);

CREATE INDEX idx_food_item_reports_food_item_created_at
    ON food_item_reports (food_item_id, created_at DESC);

CREATE INDEX idx_food_item_reports_reporter_created_at
    ON food_item_reports (reporter_user_id, created_at DESC);
