CREATE TABLE food_record_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_food_record_comments_record
        FOREIGN KEY (record_id)
        REFERENCES food_records (id),
    CONSTRAINT fk_food_record_comments_user
        FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT ck_food_record_comments_content_not_blank
        CHECK (length(trim(content)) > 0)
);

CREATE INDEX idx_food_record_comments_record_created_at
    ON food_record_comments (record_id, created_at DESC);

CREATE INDEX idx_food_record_comments_user_created_at
    ON food_record_comments (user_id, created_at DESC);
